# Generated by Django 5.1.7 on 2025-07-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='id_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id_class',
        ),
        migrations.AddField(
            model_name='students',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classe_students', to='school.classes'),
        ),
    ]
