# Generated by Django 5.1.7 on 2025-07-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_classes_name_alter_students_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='average',
        ),
    ]
