# Generated by Django 5.1.7 on 2025-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='date_attempted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
