# Generated by Django 5.1.7 on 2025-07-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='score',
            field=models.CharField(max_length=50),
        ),
    ]
