# Generated by Django 5.1.7 on 2025-07-05 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('added_date', models.DateField()),
                ('score_on', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_results', to='school.classes')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='school.students')),
                ('id_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_results', to='school.teachers')),
            ],
        ),
    ]
