# Generated by Django 5.1.7 on 2025-07-09 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_reset_token',
            name='token',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='password_reset_token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
