# Generated by Django 5.1.7 on 2025-07-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('created_at', models.DateField()),
                ('due_date', models.DateField()),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_homeworks', to='school.classes')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_homeworks', to='school.teachers')),
            ],
        ),
    ]
