# Generated by Django 5.1.7 on 2025-07-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_id_user_students_user_and_more'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworks',
            old_name='id_teacher',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='homeworks',
            name='id_class',
        ),
        migrations.AddField(
            model_name='homeworks',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_homeworks', to='school.classes'),
        ),
    ]
