# Generated by Django 5.1.7 on 2025-07-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_id_user_students_user_and_more'),
        ('works', '0002_rename_id_teacher_homeworks_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_homeworks', to='school.classes'),
        ),
    ]
