# Generated by Django 5.1.7 on 2025-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_homeworks_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
